### ISSUE TITLE
Issue with handlers with respect to the activation life-cycle

### ISSUE THREAD

**Issue by AdamWillden** [tkhyn/aurelia-flux#1]
Regarding https://github.com/tfrydrychewicz/aurelia-flux/issues/17#issuecomment-182777974: 

> @tkhyn I have a custom element (component) that uses your fork of aurelia-flux. When using an if binding on the custom element the lifecycle hooks are called. As such the handlers will work initially. Then once the element is removed and readded the handlers are not hooked up again.
> 
> Any chance of a fix for that or is aurelia-flux not in use by you anymore? Would it be simple enough?

I've created an example app from the skeleton:
https://www.dropbox.com/s/ghwbr1eweporcte/flux-issue.zip?dl=0

```
npm install
jspm install
gulp watch
```

This revealed additional info regarding the issue. The issue is two-fold:
- If the custom element specifies a `detached` callback then the handler is disposed and will not be recreated when the custom element is re-shown. 
- If the custom element **does not** specify a `detached` callback then the handler still operates even though the custom element is not on the screen.

I'd _really_ appreciate if you are able to look into this.

**Comment by AdamWillden** [comment]
When an element **does not** specify a detached callback the detached callback that aurelia-flux tries to add is never executed. I guess aurelia checks for the existence of a detached callback and whether or not it is used for lifecycle events before the aurelia-flux lifecycle-manager operates.

For instance I tried to add a detached callback dynamically but the alert was never called

``` javascript
import {inject, bindable} from 'aurelia-framework';
import {Dispatcher, handle} from 'aurelia-flux';

@inject(Dispatcher)
export class Listener {
    @bindable hasDetached = true;

    bind() {
     if(this.hasDetached) {
       this.detached = () => { alert('detached'); };
     }
    }

    @handle('eventName')
    alertEvent(action, count) {
        alert(`HasDetached: ${this.hasDetached} ::: ${action} ::: ${count}`);
    }
}
```

**Comment by AdamWillden** [comment]
With respect to the above see this code:

https://github.com/aurelia/templating/blob/842014fd6ede2ec88906158d8afff8b4ab84487c/src/html-behavior.js#L109

I suspect it's to do with the dispatch not existing on the prototype.

# UPDATE

I've just debugged and seen that the templating check for handlers occurs **BEFORE** aurelia-flux adds it's lifecycle hooks. As such making it modify the prototype is not going to be enough on its own. aurelia-flux is hooking in too late.

**I've not yet looked into the other issue where the detached hook _is_ present**

**Comment by AdamWillden** [comment]
@tkhyn Just wanted to say I've decided to ditch aurelia-flux in favour of using the event-aggregator

While I liked the `@handle` decorators aurelia-flux is simply too heavy for my requirements and as it is not really maintained (not your fault) and you can't test that the class hooks onto the events. 

While I'm pretty sure this issue exists I'm not bothered if you want to close it.

**Comment by tkhyn** [comment]
Yes, sorry for not replying I really did not have the time to do so in the last weeks.

I'll also be using my own Flux implementation soon, so I would not have maintained that long-term anyway.

**Comment by AdamWillden** [comment]
Really, it is not a problem.  I wouldn't have had the time to fix it so dont expect that you would have either. 

Thanks for making it work!
